# Generated by Django 4.2.14 on 2024-07-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_model',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('price', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
            ],
        ),
    ]
